-- MySQL Script generated by MySQL Workbench
-- Sat Sep  9 15:51:40 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema quinielas_compas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema quinielas_compas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `quinielas_compas` DEFAULT CHARACTER SET utf8mb3 ;
USE `quinielas_compas` ;

-- -----------------------------------------------------
-- Table `quinielas_compas`.`matches`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quinielas_compas`.`matches` ;

CREATE TABLE IF NOT EXISTS `quinielas_compas`.`matches` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `fkQuiniela` INT NOT NULL,
  `fkSession` INT NOT NULL,
  `fkTemaA` INT NOT NULL,
  `fkTeamB` INT NOT NULL,
  `dateMatch` TIMESTAMP(3) NOT NULL,
  `winner` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `quinielas_compas`.`quinielas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quinielas_compas`.`quinielas` ;

CREATE TABLE IF NOT EXISTS `quinielas_compas`.`quinielas` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NULL DEFAULT NULL,
  `description` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `quinielas_compas`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quinielas_compas`.`users` ;

CREATE TABLE IF NOT EXISTS `quinielas_compas`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nameUser` VARCHAR(40) NULL DEFAULT NULL,
  `email` VARCHAR(100) NOT NULL,
  `passwordUser` VARCHAR(70) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
